/**
 * Represents a chat message in the application.
 */
export interface Message {

	/**
	 * Unique identifier for the message, generated by the backend.
	 */
	id?: number;

	/**
	 * The name of the user who sent the message.
	 */
	author: string;

	/**
	 * The textual content of the message.
	 */
	content: string;

	/**
	 * URL of the sender's avatar image.
	 */
	avatar: string;

	/**
	 * The timestamp indicating when the message was sent.
	 */
	timestamp: Date;

	/**
	 * Indicates whether the message was sent by the current user.
	 * If true, the message is styled differently.
	 */
	isOwnMessage: boolean;
}
